version: '3.8'
services:
  api:
    build: ./api
    ports:
      - "8080:8080"
  web:
    build: ./web
    environment:
      - NEXT_PUBLIC_API_BASE_URL=http://api:8080
      - API_BASE_URL=http://api:8080
    ports:
      - "3000:3000"
    depends_on:
      - api
