spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: YOUR_GOOGLE_CLIENT_ID
            client-secret: YOUR_GOOGLE_CLIENT_SECRET
            scope:
              - openid
              - profile
              - email
jwt:
  secret: your-256-bit-secret-key-for-development-only-change-in-production
server:
  port: 8080
management:
  endpoints:
    web:
      exposure:
        include: '*'
