spring:
  profiles:
    active: dev
  datasource:
    url: jdbc:postgresql://localhost:5432/utro
    username: utro
    password: utro_password
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: validate
    show-sql: false
  flyway:
    enabled: true
    baseline-on-migrate: true
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: YOUR_GOOGLE_CLIENT_ID
            client-secret: YOUR_GOOGLE_CLIENT_SECRET
            scope:
              - openid
              - profile
              - email
jwt:
  secret: your-256-bit-secret-key-for-development-only-change-in-production
server:
  port: 8080
management:
  endpoints:
    web:
      exposure:
        include: '*'
  tracing:
    sampling:
      probability: 1.0
  otlp:
    tracing:
      endpoint: http://localhost:4318/v1/traces

# OpenTelemetry Configuration
otel:
  service:
    name: utro-api
    version: 0.1.0
  exporter:
    otlp:
      endpoint: http://localhost:4318
      protocol: http/protobuf
  resource:
    attributes:
      service.name: utro-api
      service.namespace: utro
      service.version: 0.1.0
      deployment.environment: development
