receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318
        cors:
          allowed_origins:
            - "http://localhost:3000"
            - "http://localhost:8080"
          allowed_headers:
            - "*"

processors:
  batch:
    timeout: 1s
    send_batch_size: 1024
  
  resource:
    attributes:
      - key: deployment.environment
        value: docker
        action: upsert
      - key: service.instance.id
        from_attribute: service.name
        action: insert

  # Add span attributes for better trace visualization
  attributes:
    actions:
      - key: http.user_agent
        action: delete
      - key: net.peer.ip
        action: delete

exporters:
  jaeger:
    endpoint: jaeger:14250
    tls:
      insecure: true

  logging:
    loglevel: debug

  # Optional: Export to OTLP endpoint (useful for other backends)
  otlp:
    endpoint: jaeger:4317
    tls:
      insecure: true

service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [resource, attributes, batch]
      exporters: [jaeger, logging]

  extensions: []

  telemetry:
    logs:
      level: "debug"
    metrics:
      address: 0.0.0.0:8888